version: "3.8"
services:
    lms-db-mongo: 
        image: mongo:5.0.6
        container_name: lms-db-mongo
        restart: always
        ports:
            - $LMS_MONGO_HOST_PORT:27017
        networks:
            - yo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=$MONGO_ROOT_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
            - MONGO_INITDB_DATABASE=$MONGO_APP_DB_NAME
            - MONGO_DB_USERNAME=$MONGO_APP_DB_USERNAME
            - MONGO_DB_PASSWORD=$MONGO_APP_DB_PASSWORD
        volumes:
            - $MONGO_DATA_HOST_PATH:/data/db
            - $MONGO_LOG_HOST_PATH:/var/log/mongodb
            - $MONGO_INITDB_SCRIPTS_HOST_PATH:/docker-entrypoint-initdb.d
        command: ["--bind_ip","0.0.0.0"]
    lms-ui-db-postgres:
        image: postgres:14
        container_name: lms-ui-db-postgres
        restart: always
        ports:
            - $LMSUI_POSTGRES_HOST_PORT:5432
        networks:
            - yo
        environment:
            - POSTGRES_USER=$POSTGRES_ROOT_USERNAME
            - POSTGRES_PASSWORD=$POSTGRES_ROOT_PASSWORD
            - APP_DB_USER=$POSTGRES_APP_DB_USERNAME
            - APP_DB_PASS=$POSTGRES_APP_DB_PASSWORD
            - APP_DB_NAME=$POSTGRES_APP_DB_NAME
        volumes:
            - $POSTGRES_DATA_HOST_PATH:/var/lib/postgresql/data
            - $POSTGRES_LOG_HOST_PATH:/var/log/postgresql
            - $POSTGRES_INITDB_SCRIPTS_HOST_PATH:/docker-entrypoint-initdb.d
    
    eureka-server-1:
        image: eureka-naming-server:0.0.1-SNAPSHOT
        container_name: eureka-server-1
        mem_limit: 700m
        ports:
            - $EUREKA_NAMING_SERVER_1_HOST_PORT:$EUREKA_NAMING_SERVER_PORT
        networks:
            - yo
        environment:
            - server.port=$EUREKA_NAMING_SERVER_PORT
            - spring.application.name=eureka-server-1
            - eureka.instance.hostname=eureka-server-1
            - eureka.client.register-with-eureka=false
            - eureka.client.fetch-registry=false

    
    lms-app-1:
        image: library-management-system:0.0.1-SNAPSHOT
        container_name: lms-app-1
        mem_limit: 700m
        restart: on-failure:10
        ports:
            - $LMS_APP_1_HOST_PORT:$LMS_APP_PORT
        networks:
            - yo
        depends_on:
            - lms-db-mongo
            - eureka-server-1
        environment:
            - server.port=$LMS_APP_PORT
            - spring.application.name=$LMS_APP_NAME
            - spring.data.mongodb.host=lms-db-mongo
            - spring.data.mongodb.port=27017
            - spring.data.mongodb.database=$MONGO_APP_DB_NAME
            - spring.data.mongodb.username=$MONGO_APP_DB_USERNAME
            - spring.data.mongodb.password=$MONGO_APP_DB_PASSWORD
            - spring.data.mongodb.authentication-database=$MONGO_APP_DB_NAME
            - management.endpoints.web.exposure.include=*
            - management.endpoint.health.show-details=always
            - management.endpoint.health.group.lms-app-database-health-group.include=diskSpace,mongo
            - management.info.env.enabled=true
            - management.endpoints.web.base-path=/actuator
            - management.endpoints.web.path-mapping.health=health
            - eureka.instance.prefer-ip-address=true
            - eureka.client.fetch-registry=true
            - eureka.client.register-with-eureka=true
            - eureka.client.service-url.defaultZone=http://eureka-server-1:8761/eureka
            
            
    lms-app-ui-1:
        image: library-management-ui:0.0.1-SNAPSHOT
        container_name: lms-app-ui-1
        restart: always
        mem_limit: 700m
        ports:
            - $LMS_UI_1_HOST_PORT:$LMS_UI_PORT
        depends_on:
            - lms-ui-db-postgres
            - eureka-server-1
            - lms-app-1
        networks:
            - yo
        environment:
            - server.port=$LMS_UI_PORT
            - spring.application.name=$LMS_UI_NAME
            - lms.app.user=lmsuser1
            - lms.app.user.password=l1m2s3p4a%s^s&w&o*r(d
            - spring.jpa.database=postgresql
            - spring.jpa.hibernate.ddl-auto=update
            - spring.jpa.show-sql=true
            - spring.jpa.defer-datasource-initialization=true
            - spring.jpa.hibernate.naming.implicit-strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
            - spring.jpa.hibernate.naming.physical-strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
            - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect
            - spring.datasource.driver-class-name=org.postgresql.Driver
            - spring.datasource.tomcat.test-while-idle=true
            - spring.datasource.tomcat.validation-query=SELECT 1
            - spring.datasource.url=jdbc:postgresql://lms-ui-db-postgres:5432/lms_ui_app
            - spring.datasource.username=lmsuipguser
            - spring.datasource.password=lmsuipgpassword
            - eureka.client.register-with-eureka=true
            - eureka.client.fetch-registry=true
            - eureka.client.serviceUrl.defaultZone=http://eureka-server-1:8761/eureka
            - feign.httpclient.enabled=false
networks:
    yo:
            
